secretsprovider: gcpkms://projects/branchleft-prod/locations/europe-west1/keyRings/pulumi/cryptoKeys/pulumi-secrets
encryptedkey: CiQAefexUjhJqs77slYC36RbQuiTMskcVdnP+pt6SdHOE69NBi4SSQBxixxQqR87u6ZOp/OVy/OquxHOBVjW0LR7NIZ1GV+tBF+pdyrpKPqznApFZTH9jBZL+Umq6SOCMEmKRrYaHM1IIvUfHP5yx50=
config:
  gcp:project: branchleft-prod
