#!/usr/bin/env python3
"""Renders the static systemd template unit for the demo slots' health routers.

Usage: render_router_unit.py [--install DIR]

Prints the unit, or with `--install` writes `branchleft-health-router@.service`
under DIR (the host-build form, DIR being /etc/systemd/system), root-owned.
Run `systemctl daemon-reload` afterwards, then enable one instance per slot.
See render_router_unit.md for why the unit names no colour unit.
"""

from __future__ import annotations

import argparse
import os
import sys
import tempfile

from health_router import ROUTER_USER

UNIT_NAME = "branchleft-health-router@.service"
UNIT_MODE = 0o644
ROUTER_SCRIPT = "/usr/local/lib/branchleft/health_router.py"


def render() -> str:
    return f"""# Slot %i's health router, generated by render_router_unit.py. Do not hand-edit.
# Static: it names no colour unit, so no colour's start, stop or failure moves it.
[Unit]
Description=Demo slot %i health router

[Service]
Type=simple
User={ROUTER_USER}
Group={ROUTER_USER}
ExecStart=/usr/bin/python3 {ROUTER_SCRIPT} --slot %i
Restart=always
RestartSec=2
NoNewPrivileges=yes
CapabilityBoundingSet=
ProtectSystem=strict
ProtectHome=yes
PrivateTmp=yes
PrivateDevices=yes
ProtectKernelTunables=yes
ProtectKernelModules=yes
ProtectControlGroups=yes
RestrictAddressFamilies=AF_INET AF_UNIX
IPAddressAllow=localhost
IPAddressDeny=any
InaccessiblePaths=-/run/docker.sock -/var/run/docker.sock
MemoryDenyWriteExecute=yes
LockPersonality=yes
RestrictRealtime=yes
SystemCallFilter=@system-service

[Install]
WantedBy=multi-user.target
"""


def install(root: str) -> str:
    """Writes the unit under `root`; requires root, because a unit systemd
    reads from a directory it does not own is one it may ignore."""
    os.makedirs(root, exist_ok=True)
    path = os.path.join(root, UNIT_NAME)
    fd, tmp = tempfile.mkstemp(dir=root, prefix=".router-")
    try:
        with os.fdopen(fd, "w") as handle:
            handle.write(render())
        os.chmod(tmp, UNIT_MODE)
        os.chown(tmp, 0, 0)
        os.replace(tmp, path)
    except BaseException:
        if os.path.exists(tmp):
            os.remove(tmp)
        raise
    return path


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--install", metavar="DIR", help="write the unit under DIR (root)")
    args = parser.parse_args(argv)
    if args.install is not None:
        path = install(args.install)
        print(f"wrote {path}; run systemctl daemon-reload")
    else:
        sys.stdout.write(render())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
