#!/usr/bin/env python3
"""Render the demo host's sudoers boundary from the slot table.

Usage:
    render_slot_sudoers.py [--out FILE]

Prints the generated sudoers file to stdout, or installs it at `--out`
(syntax-checked with `visudo -c -f` and written atomically -- see
`write_generated_file`).

The demo host's broker runs as an unprivileged user and needs root for
exactly one thing: starting, stopping or resetting a slot's systemd units.
The set of legal invocations is finite and known before any prospect exists
-- fixed slots, two colours, three verbs -- so the boundary can enumerate
every one of them literally rather than accept a pattern. A wildcard in a
sudoers command matches spaces, which turns any pattern-based restriction
into argument injection the moment something reaches it; enumeration has no
pattern to subvert.

This module is the single source of truth for that enumeration: the slot
table below, not thirty-five hand-typed sudoers lines. Extending the slot
count means adding to the table, not editing generated output by hand.

**What sudoers actually binds, and what it does not.** sudo compares the
space-joined text of the command it is given against each sudoers command
as a literal string -- it does not compare argument by argument. So
`sudo /usr/local/sbin/branchleft-slot '0 reset'`, passed as a single quoted
shell argument, produces the same space-joined text as the intended
two-argument `<slot> reset` invocation and is permitted by this file, even
though the wrapper then receives one argument (`"0 reset"`) rather than
two. No sudoers syntax can pin the split -- sudoers has no notion of
argument boundaries to pin, only the string it is compared against. The
wrapper (built separately from this generator) must therefore reject
anything that is not exactly two or three distinct arguments, each matching
its own literal shape -- a known slot name, then either `reset` alone or a
colour in `{a,b}` followed by `start`/`stop`. That is the second layer the
design already calls for; this file cannot do that job structurally, so the
wrapper has to.
"""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
import tempfile
from typing import Sequence

# The forced-command wrapper this rule grants root for, and the account the
# rule is written against. Both are literal strings in every generated line
# -- neither is ever templated from anything a caller supplies.
WRAPPER_PATH = "/usr/local/sbin/branchleft-slot"
BROKER_USER = "broker"

# The slot table. Each entry is a slot's own literal name -- the wrapper's
# first argument -- not an array index, so reordering this tuple can never
# renumber a slot underfoot. Slot count is a host-build parameter: adding an
# eighth slot here is the entire change needed to enumerate it.
SLOT_NAMES: tuple[str, ...] = tuple(str(n) for n in range(7))

# A slot is a colour pair (two independently startable/stoppable Ghost
# containers sharing one uid, directory and dataset), plus one slot-level
# reset that stops and wipes both colours at once. Reset takes no colour
# because it destroys the tenancy rather than a single container.
COLOURS: tuple[str, ...] = ("a", "b")
START_STOP_VERBS: tuple[str, ...] = ("start", "stop")

# A slot name reaches sudoers as a literal string, so it must be exactly
# what the wrapper's argv-parsing expects and nothing more -- a slot name
# carrying a space, a glob character or anything else would either fail to
# match its own rule or, worse, change what the rule matches.
SLOT_NAME_PATTERN = re.compile(r"\A[0-9]+\Z")

HEADER_COMMENT_LINES: tuple[str, ...] = (
    "# Generated by render_slot_sudoers.py from the slot table -- edit the",
    "# table, not this file.",
    "",
    "# Every command below is a literal invocation, enumerated rather than",
    "# matched: a wildcard in a sudoers command matches spaces, so a pattern",
    "# here would let an extra argument reach the wrapper as root.",
)


class InvalidSlotName(ValueError):
    """Raised for a slot-table entry that is not a bare digit string."""


def _validate_slot_name(slot: str) -> None:
    if not SLOT_NAME_PATTERN.match(slot):
        raise InvalidSlotName(
            f"slot name {slot!r} must be one or more digits and nothing else -- sudoers "
            "matches it literally, so anything else changes what the generated rule matches"
        )


def slot_invocations(slot: str) -> list[str]:
    """The five legal wrapper argument strings for one slot.

    Reset first, then colour x verb in a stable order, so the generated
    file's diff between runs is confined to whichever slots actually
    changed.
    """
    _validate_slot_name(slot)
    invocations = [f"{slot} reset"]
    for colour in COLOURS:
        for verb in START_STOP_VERBS:
            invocations.append(f"{slot} {colour} {verb}")
    return invocations


def all_invocations(slots: Sequence[str] = SLOT_NAMES) -> list[str]:
    """Every legal invocation across every slot, in slot-table order."""
    result: list[str] = []
    for slot in slots:
        result.extend(slot_invocations(slot))
    return result


def render(slots: Sequence[str] = SLOT_NAMES) -> str:
    """Build the sudoers file's full text.

    One NOPASSWD rule per invocation, each command a literal, fully
    space-delimited argument list, nothing else in the file at all.
    """
    lines = list(HEADER_COMMENT_LINES) + [""]
    for invocation in all_invocations(slots):
        lines.append(f"{BROKER_USER} ALL=(root) NOPASSWD: {WRAPPER_PATH} {invocation}")
    lines.append("")
    return "\n".join(lines)


def write_generated_file(path: str, content: str) -> None:
    """Install `content` at `path` the way a host build must: to a temp file
    in the same directory, syntax-checked with `visudo -c -f` before
    anything can read it, then renamed into place atomically.

    `visudo -c -f` checks syntax only -- it does not check the file's mode.
    A file at 0644 parses exactly as one at 0440 does; it is
    `visudo -c` against the *whole active configuration* (no `-f`) that
    refuses a sudoers.d file with the wrong permissions, and only once it is
    already installed. So the 0440 below is this function's own guarantee,
    not something a syntax check would have caught for it.

    On any failure the temp file is removed and `path` is left untouched --
    a partial or invalid write never reaches the install path.
    """
    directory = os.path.dirname(os.path.abspath(path)) or "."
    fd, tmp_path = tempfile.mkstemp(dir=directory, prefix=".render_slot_sudoers-")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(content)
        os.chmod(tmp_path, 0o440)
        try:
            result = subprocess.run(
                ["visudo", "-c", "-f", tmp_path], capture_output=True, text=True
            )
        except FileNotFoundError as exc:
            raise RuntimeError(
                "visudo is required to install the generated file safely; it was not found "
                "on PATH"
            ) from exc
        if result.returncode != 0:
            raise RuntimeError(
                "visudo -c -f rejected the generated file; nothing was installed:\n"
                f"{result.stdout}{result.stderr}"
            )
        os.replace(tmp_path, path)
    except BaseException:
        if os.path.exists(tmp_path):
            os.remove(tmp_path)
        raise


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out",
        help=(
            "path to install the generated file at, syntax-checked and written "
            "atomically; defaults to printing to stdout with no check"
        ),
    )
    args = parser.parse_args(argv)
    content = render()
    if args.out is None:
        sys.stdout.write(content)
    else:
        write_generated_file(args.out, content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
