#!/usr/bin/env python3
"""Renders the per-colour systemd drop-ins for the demo host's slots.

Usage: render_colour_units.py [--install DIR]

Prints every drop-in, or with `--install` writes them under DIR (the
host-build form, DIR being /etc/systemd/system), root-owned. Run
`systemctl daemon-reload` afterwards. See render_colour_units.md for what a
drop-in changes in the generic `branchleft-compose@` template and why the
unit names stay exactly as the sudoers file enumerates them.
"""

from __future__ import annotations

import argparse
import os
import sys
import tempfile
from typing import Sequence

from branchleft_slot import COLOURS, SLOT_DIR, UNIT_TEMPLATE
from render_slot_sudoers import SLOT_NAMES

ETC_DIR = "/etc/branchleft"
DROPIN_NAME = "colour.conf"
DROPIN_MODE = 0o644


def instance(slot: str, colour: str) -> str:
    return UNIT_TEMPLATE.format(slot=slot, colour=colour)


def dropin_path(root: str, slot: str, colour: str) -> str:
    return os.path.join(root, f"{instance(slot, colour)}.service.d", DROPIN_NAME)


def render(slot: str, colour: str) -> str:
    """The drop-in for one (slot, colour). Every list-valued directive the
    template sets is cleared with an empty assignment before being set
    again: systemd appends to them otherwise, which would leave the
    template's own `/etc/branchleft/%i.image.env` requirement and its
    registry pull in force for an instance that has neither."""
    if slot not in SLOT_NAMES:
        raise ValueError(f"unknown slot {slot!r}")
    if colour not in COLOURS:
        raise ValueError(f"unknown colour {colour!r}")
    slot_dir = SLOT_DIR.format(slot=slot)
    service = f"ghost-{colour}"
    return f"""# One colour of one slot, generated by render_colour_units.py. Do not hand-edit.
[Unit]
AssertPathExists=
AssertPathExists={slot_dir}/compose.yml
AssertPathExists={slot_dir}/image.env

[Service]
WorkingDirectory=
WorkingDirectory={slot_dir}
EnvironmentFile=
EnvironmentFile={slot_dir}/image.env
EnvironmentFile=-{ETC_DIR}/demo-{slot}-{colour}.env
ExecStartPre=
ExecStart=
ExecStart=/usr/bin/docker compose up -d --wait {service}
ExecStop=/usr/bin/docker compose stop {service}
ExecStopPost=/usr/bin/docker compose stop {service}
"""


def render_all() -> dict[str, str]:
    """Keyed by instance name, in slot then colour order."""
    return {instance(s, c): render(s, c) for s in SLOT_NAMES for c in COLOURS}


def _write(path: str, content: str) -> None:
    directory = os.path.dirname(path)
    os.makedirs(directory, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=directory, prefix=".colour-")
    try:
        with os.fdopen(fd, "w") as handle:
            handle.write(content)
        os.chmod(tmp, DROPIN_MODE)
        os.chown(tmp, 0, 0)
        os.replace(tmp, path)
    except BaseException:
        if os.path.exists(tmp):
            os.remove(tmp)
        raise


def install(root: str) -> list[str]:
    """Writes every drop-in under `root`; requires root, because a drop-in
    systemd reads from a directory it does not own is one it may ignore or
    one anyone could replace."""
    paths: list[str] = []
    for slot in SLOT_NAMES:
        for colour in COLOURS:
            path = dropin_path(root, slot, colour)
            _write(path, render(slot, colour))
            paths.append(path)
    return paths


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--install", metavar="DIR", help="write the drop-ins under DIR (root)")
    args = parser.parse_args(argv)
    if args.install is not None:
        paths = install(args.install)
        print(f"wrote {len(paths)} drop-in(s) under {args.install}; run systemctl daemon-reload")
    else:
        for name, content in render_all().items():
            sys.stdout.write(f"## {name}\n{content}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
