#!/usr/bin/env python3
"""Render the demo host's edge upstream block from the slot table.

Usage: render_demo_edge.py [--out FILE]

Prints the generated Caddyfile fragment to stdout, or writes it atomically
to `--out`. See render_demo_edge.md for what the snippet does and does not
bind, and which of its values are load-bearing rather than per-host
configuration.
"""

from __future__ import annotations

import argparse
import os
import re
import sys
import tempfile
from typing import Sequence

from render_slot_sudoers import SLOT_NAMES

# The demo edge runs in demo1's own host network namespace (LLD-2 §01b,
# amended 2026-09-23): every slot's colour ports and health port are on the
# host's own loopback, never a container-bridge address, which is what lets
# this one process reach all seven slots' sidecars through their shared
# health ports at all.
DEMO_EDGE_ADDR = "127.0.0.1"

# Mirrors `services/broker/src/config.ts`'s own `BROKER_APP_PORT_BASE` /
# `BROKER_HEALTH_PORT_BASE` defaults -- kept as a separate literal here
# deliberately, the same reasoning `render_slot_sudoers.py`'s own header
# gives for not reading that file at runtime: this generator and the broker
# are different processes in different languages, each host-build
# parameter has exactly one authoritative default, and duplicating it with
# a comment is how this codebase already keeps `slotPorts.ts` and
# `config.ts` themselves from silently drifting apart. If a host ever
# overrides `BROKER_APP_PORT_BASE`/`BROKER_HEALTH_PORT_BASE`, whatever
# regenerates this file must be told the same override.
APP_PORT_BASE = 9300
HEALTH_PORT_BASE = 9100

# LLD-4 §U3b, load-bearing: "Set it to 2s, and treat that number as
# load-bearing rather than a tuning detail: it is the whole distance
# between a flag change and traffic moving."
HEALTH_INTERVAL = "2s"
HEALTH_URI = "/healthz"
# The header name is incidental (LLD-2 §06's table: "as may the header's
# name and what implements the router"); pinned as one constant here so a
# future rename touches this file and the router's own config in the same
# place rather than drifting.
COLOUR_HEADER = "X-Colour-Upstream"

HEADER_COMMENT_LINES: tuple[str, ...] = (
    "# Generated by render_demo_edge.py from the slot table -- edit the",
    "# table, not this file.",
    "#",
    "# Each slot's own named snippet holds only what LLD-2 §01 allocates once",
    "# at host build: the colour pair's app ports and the slot's one shared",
    "# health port. Whatever binds this slot's current hostname imports the",
    "# matching snippet; reconcile never edits this file (LLD-2 §01b).",
)

SLOT_NAME_PATTERN = re.compile(r"\A[0-9]+\Z")


class InvalidSlotName(ValueError):
    """Raised for a slot-table entry that is not a bare digit string."""


def _validate_slot_name(slot: str) -> None:
    if not SLOT_NAME_PATTERN.match(slot):
        raise InvalidSlotName(
            f"slot name {slot!r} must be one or more digits and nothing else -- it names "
            "this slot's own snippet and ports, so anything else changes what gets generated"
        )


def slot_app_port(slot: str, colour: str) -> int:
    """`appPortBase + slot*2 (+1 for colour "b")` -- `services/broker/src/slotPorts.ts`'s
    `slotPort`, mirrored (see this module's own docstring on why a mirror rather than a
    shared source)."""
    _validate_slot_name(slot)
    if colour not in ("a", "b"):
        raise ValueError(f'colour must be "a" or "b", got {colour!r}')
    return APP_PORT_BASE + int(slot) * 2 + (1 if colour == "b" else 0)


def slot_health_port(slot: str) -> int:
    """`healthPortBase + slot` -- mirrors `slotPorts.ts`'s `slotHealthPort`."""
    _validate_slot_name(slot)
    return HEALTH_PORT_BASE + int(slot)


def snippet_name(slot: str) -> str:
    _validate_slot_name(slot)
    return f"slot{slot}-upstream"


def render_slot_snippet(slot: str) -> str:
    """One slot's named snippet, importable from whatever site block binds
    this slot's current hostname. `lb_policy first` plus "a new colour
    always boots drained" (LLD-2 §01b, enforced by the broker, not this
    file) is what makes the swap work in both directions -- see
    `services/broker/src/app.ts`'s `attemptColourSwap`.
    """
    a_port = slot_app_port(slot, "a")
    b_port = slot_app_port(slot, "b")
    health_port = slot_health_port(slot)
    return "\n".join(
        [
            f"({snippet_name(slot)}) {{",
            f"\treverse_proxy {DEMO_EDGE_ADDR}:{a_port} {DEMO_EDGE_ADDR}:{b_port} {{",
            "\t\tlb_policy first",
            f"\t\thealth_uri {HEALTH_URI}",
            # The router in front of the two sidecars, not Ghost -- LLD-4 §U3b.
            f"\t\thealth_port {health_port}",
            f"\t\thealth_interval {HEALTH_INTERVAL}",
            "\t\thealth_headers {",
            f"\t\t\t{COLOUR_HEADER} {{http.reverse_proxy.active.target_upstream}}",
            "\t\t}",
            "\t}",
            "}",
        ]
    )


def render(slots: Sequence[str] = SLOT_NAMES) -> str:
    """The full generated fragment: the edge's one global-options block,
    then every slot's own named snippet, in slot-table order.

    `admin off` (LLD-2 §01b, amended): host networking exposes Caddy's
    otherwise-unauthenticated admin API to every other process on demo1,
    and this edge's configuration is generated once and never reloaded, so
    the endpoint has no job here.
    """
    lines = list(HEADER_COMMENT_LINES) + [
        "{",
        "\tadmin off",
        "}",
        "",
    ]
    for slot in slots:
        lines.append(render_slot_snippet(slot))
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def write_generated_file(path: str, content: str) -> None:
    """Writes `content` to `path` atomically -- a temp file in the same
    directory, renamed into place -- so a reader (or the edge's own next
    start) never observes a partial write. See the module docstring for why
    this has no pre-write syntax check the way `render_slot_sudoers.py`'s
    `visudo -c -f` does.
    """
    directory = os.path.dirname(os.path.abspath(path)) or "."
    fd, tmp_path = tempfile.mkstemp(dir=directory, prefix=".render_demo_edge-")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(content)
        os.replace(tmp_path, path)
    except BaseException:
        if os.path.exists(tmp_path):
            os.remove(tmp_path)
        raise


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out",
        help="path to write the generated fragment to, atomically; defaults to stdout",
    )
    args = parser.parse_args(argv)
    content = render()
    if args.out is None:
        sys.stdout.write(content)
    else:
        write_generated_file(args.out, content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
