#!/usr/bin/env python3
"""Render the demo host's sudoers boundary from the slot table.

Usage:
    render_slot_sudoers.py [--out FILE]

Prints the generated sudoers file to stdout, or writes it to `--out`.

The demo host's broker runs as an unprivileged user and needs root for
exactly one thing: starting, stopping or resetting a slot's systemd units.
The set of legal invocations is finite and known before any prospect exists
-- fixed slots, two colours, three verbs -- so the boundary can enumerate
every one of them literally rather than accept a pattern. A wildcard in a
sudoers command matches spaces, which turns any pattern-based restriction
into argument injection the moment something reaches it; enumeration has no
pattern to subvert.

This module is the single source of truth for that enumeration: the slot
table below, not thirty-five hand-typed sudoers lines. Extending the slot
count means adding to the table, not editing generated output by hand --
the file this script produces is never edited directly, since cloud-init
regenerates it at host build and a hand edit would be silently overwritten.
"""

from __future__ import annotations

import argparse
import sys
from typing import Sequence

# The forced-command wrapper this rule grants root for, and the account the
# rule is written against. Both are literal strings in every generated line
# -- neither is ever templated from anything a caller supplies.
WRAPPER_PATH = "/usr/local/sbin/branchleft-slot"
BROKER_USER = "broker"

# The slot table. Each entry is a slot's own literal name -- the wrapper's
# first argument -- not an array index, so reordering this tuple can never
# renumber a slot underfoot. Slot count is a host-build parameter: adding an
# eighth slot here is the entire change needed to enumerate it.
SLOT_NAMES: tuple[str, ...] = tuple(str(n) for n in range(7))

# A slot is a colour pair (two independently startable/stoppable Ghost
# containers sharing one uid, directory and dataset), plus one slot-level
# reset that stops and wipes both colours at once. Reset takes no colour
# because it destroys the tenancy rather than a single container.
COLOURS: tuple[str, ...] = ("a", "b")
START_STOP_VERBS: tuple[str, ...] = ("start", "stop")


def slot_invocations(slot: str) -> list[str]:
    """The five legal wrapper argument strings for one slot.

    Reset first, then colour x verb in a stable order, so the generated
    file's diff between runs is confined to whichever slots actually
    changed.
    """
    invocations = [f"{slot} reset"]
    for colour in COLOURS:
        for verb in START_STOP_VERBS:
            invocations.append(f"{slot} {colour} {verb}")
    return invocations


def all_invocations(slots: Sequence[str] = SLOT_NAMES) -> list[str]:
    """Every legal invocation across every slot, in slot-table order."""
    result: list[str] = []
    for slot in slots:
        result.extend(slot_invocations(slot))
    return result


def render(slots: Sequence[str] = SLOT_NAMES) -> str:
    """Build the sudoers file's full text.

    One NOPASSWD rule per invocation, each command a literal, fully
    space-delimited argument list -- nothing the wrapper's argv can
    disagree with, and nothing for a later hand edit to widen without the
    line itself changing shape.
    """
    lines = [
        "# Generated file -- do not edit by hand. Regenerated by cloud-init at",
        "# host build from the slot table; a hand edit is overwritten, not kept.",
        "#",
        "# Every command below is a literal invocation, enumerated rather than",
        "# matched: a wildcard in a sudoers command matches spaces, so a pattern",
        "# here would let an extra argument reach the wrapper as root.",
        "",
    ]
    for invocation in all_invocations(slots):
        lines.append(f"{BROKER_USER} ALL=(root) NOPASSWD: {WRAPPER_PATH} {invocation}")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out",
        help="file to write the generated sudoers content to; defaults to stdout",
    )
    args = parser.parse_args(argv)
    content = render()
    if args.out is None:
        sys.stdout.write(content)
    else:
        with open(args.out, "w", encoding="utf-8") as handle:
            handle.write(content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
